### ISSUE TITLE
receiving '503' / resource not found from maven

### ISSUE THREAD

**Issue by kingfish777** [ziy/medline-indexer#1]
Howdy, 
I am seeing a '503' / resource not found from maven install from edu.cmu.lti.oaqa. 
Would it be possible for the developers to bundle up the github for the open source question answering github repo to which I believe the oaqa in the pom.xml is pointing? 
Thanks!
Scott Malec, CMU '10

**Comment by ziy** [comment]
Sorry for the late response. Actually that legacy repository is not used. I have just removed that repo from the pom and updated the README file. Please check it out.
