### ISSUE TITLE
missing exec goal in pom.xml

### ISSUE THREAD

**Issue by kingfish777** [ziy/medline-indexer#2]
Hi ziy,
I think that the pom.xml may be missing exec goal statement.
This is what happens when I run the medline-indexer: 

```
mvn -Ddocs.dir=../datafiles -Dindex.dir=../medline_index exec:exec@index
yup
[ERROR] Could not find goal 'exec@index' in plugin org.codehaus.mojo:exec-maven-plugin:1.5.0 among available goals exec, help, java -> [Help 1]
```

Best,
kingfish777

**Comment by ziy** [comment]
Please check out http://stackoverflow.com/questions/8252107/is-it-possible-to-execute-two-different-maven-exec-maven-plugin-in-a-single-pom: you should have Maven version > 3.3.1.

**Comment by kingfish777** [comment]
Thanks!
