### ISSUE TITLE
bug:: medline indexer can't store and index file

### ISSUE THREAD

**Issue by noyessie** [ziy/medline-indexer#4]
When

 I run medline-indexer to store my medline files, My sqlite db still empty. It is normal?

This is my output:

> mvn

> 
>  -Ddocs.dir=./../data/pubmed -Ddb.path=./../data/store/db.db3 exec:exec@store
> [INFO] Scanning for projects...
> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for edu.cmu.lti.oaqa.bio.index.medline:medline-indexer:jar:0.0.1-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 132, column 12
> [WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 84, column 12
> [WARNING] 
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING] 
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING] 
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Medline Indexer 0.0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- exec-maven-plugin:1.6.0:exec (store) @ medline-indexer ---
> Storing medline17n0001.xml.gz... +0/-0 22,71 s
> Storing medline17n0002.xml.gz... +0/-0 20,29 s
> Storing medline17n0003.xml.gz... +0/-0 14,81 s
> Storing medline17n0004.xml.gz... +0/-0 10,87 s
> Storing medline17n0005.xml.gz... +0/-0 13,70 s
> Storing medline17n0006.xml.gz... +0/-0 11,54 s
> Storing medline17n0007.xml.gz... +0/-0 10,43 s
> .....
> Storing medline17n0008.xml.gz... +0/-0 9,167 s
> toring medline17n0357.xml.gz... +0/-0 12,31 s
> Storing medline17n0358.xml.gz... +0/-0 8,205 s
> Storing medline17n0359.xml.gz... +0/-0 10,53 s
> Storing medline17n0360.xml.gz... +0/-0 12,70 s
> Storing medline17n0361.xml.gz... +0/-0 8,284 s
> Storing medline17n0362.xml.gz... +0/-0 17,40 s
> Storing medline17n0363.xml.gz... +0/-0 11,93 s
> Optimizing... 56,43 μs
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 51:42 min
> [INFO] Finished at: 2017-04-12T10:11:30+01:00
> [INFO] Final Memory: 10M/150M
> [INFO] ------------------------------------------------------------------------
> 

but my file db.db3 still empty.

**Comment by noyessie** [comment]
may i know how or is a problems ?

**Comment by noyessie** [comment]
I found the error. maybe the schema of medline files is changed, but and i think, it is a bug.

in fact, this is the schema of medline file:

```
<PubmedArticleSet>
  <PubmedArticle>
    <MedlineCitation Status="MEDLINE" Owner="NLM">
      <PMID Version="1">1</PMID>
      <DateCreated>
        <Year>1976</Year>
        <Month>01</Month>
        <Day>16</Day>
      </DateCreated>
      <DateCompleted>
        <Year>1976</Year>
        <Month>01</Month>
        <Day>16</Day>
      </DateCompleted>
      <DateRevised>
        <Year>2016</Year>
        <Month>12</Month>
        <Day>03</Day>
      </DateRevised>
      <Article PubModel="Print">
        <Journal>
          <ISSN IssnType="Print">0006-2944</ISSN>
          <JournalIssue CitedMedium="Print">
            <Volume>13</Volume>
            <Issue>2</Issue>
            <PubDate>
              <Year>1975</Year>
              <Month>Jun</Month>
            </PubDate>
          </JournalIssue>
          <Title>Biochemical medicine</Title>
          <ISOAbbreviation>Biochem Med</ISOAbbreviation>
        </Journal>
        <ArticleTitle>Formate assay in body fluids: application in methanol poisoning.</ArticleTitle>
        <Pagination>
          <MedlinePgn>117-26</MedlinePgn>
        </Pagination>
        <AuthorList CompleteYN="Y">
```

and inside the code, I found this line:

> citations = rootNode.getChildreen(MEDLINE_CITATION_ELEMENT);

in accordance with documentation of `jdom 2.0.2` and the xml schema of medline file, we can't get the medline citation with this code because method `getchildreen` return the direct childreen element.


`
getChildreen: 
This returns a List of all the child elements nested directly (one level deep) within this element with the given local name and belonging to no namespace, returned as Element objects. If this target element has no nested elements with the given name outside a namespace, an empty List is returned. The returned list is "live" in document order and changes to it affect the element's actual contents.`

to solve that, i used this code:

```

private static final Filter MEDLINE_CITATION_ELEMENT_FiLTER = new ElementFilter(MEDLINE_CITATION_ELEMENT);
citations = rootNode.getDescendants(MEDLINE_CITATION_ELEMENT_FILTER)
```

regard .!!!

**Comment by ziy** [comment]
@noyessie Could you specify where you got the xml file? I just looked at the latest medline sample file from their official website: https://www.nlm.nih.gov/databases/dtd/medsamp2016.xml. This file has the same schema as the one I used for testing: https://github.com/ziy/medline-indexer/blob/master/src/test/resources/medline/xml/medsamp2014.xml.

**Comment by noyessie** [comment]
According to installation guide of bioasqa, I following this link: [https://www.nlm.nih.gov/databases/download/pubmed_medline.html](https://www.nlm.nih.gov/databases/download/pubmed_medline.html).

On that page the medline sample data is that: ftp://ftp.ncbi.nlm.nih.gov/pubmed/.baseline-2017-sample/ and is different from file you specified above.

please regard.

**Comment by ziy** [comment]
@noyessie You are right. I can confirm that the latest baseline files have the same format as yours, and actually in the http://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_170101.dtd file, it mentioned that they've made a change on the schema on 2016-10-31.

**Comment by noyessie** [comment]
Right!!

It is not a major changes. 

Thanks for your works.
